### ISSUE TITLE
Seleccionar listado de participantes

### ISSUE THREAD

**Issue by GudarJs** [PyBAQ/atenea#10]
Como organizador quiero **revisar las aplicaciones de los asistentes y seleccionar a los que participaran en el evento** para tener el listado exacto de los participantes.

### Criterios de aceptacion

* Ver en una tabla la informacion relevante de cada aplicacion.
* Leer los datos de las aplicaciones desde google spreadsheet o desde un archivo csv.
* Seleccionar los asistentes que participaran en el evento.
* Guardar los asistentes seleccionados en una lista en mailchimp.

**Comment by pyjavo** [comment]
La idea es usar formularios tipo https://www.papercall.io/events
